### ISSUE TITLE
RoutingError for images

### ISSUE THREAD

**Issue by i-public** [codevise/pageflow-before-after#7]
I "installed" before-after (and external-links) and get following error after using it for a page in a test entry.
<pre>
F, [2015-01-12T10:56:59.111747 #25319] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/images/pageflow/before_after_pictogram.png"):
  actionpack (4.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `block in tagged'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:25:in `tagged'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `tagged'
  railties (4.0.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.2) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.2) lib/rails/engine.rb:511:in `call'
  railties (4.0.2) lib/rails/application.rb:97:in `call'
  /home/ipublic/.rvm/gems/ruby-2.1.4/gems/passenger-4.0.53/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /home/ipublic/.rvm/gems/ruby-2.1.4/gems/passenger-4.0.53/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /home/ipublic/.rvm/gems/ruby-2.1.4/gems/passenger-4.0.53/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /home/ipublic/.rvm/gems/ruby-2.1.4/gems/passenger-4.0.53/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
</pre>

It was possible to use before-after to assign to a page, after getting back to entries-admin an reenter editor I only get a white page. When I trie to preview the entry the error occurs.

**Comment by i-public** [comment]
additional: I get the same error for external-links images

**Comment by tf** [comment]
Looks like Rails is still using an obsolete cached stylesheet fragment in your application. When Sass is compiled, `image-url('foo.png')` gets expanded to the correct asset path. If the file is not found `"images/foo.png"` is used as a best guess. The file above does exist, so I suspect Rails just did not regenerate the stylesheet correctly.

Try deleting `tmp/cache/assets` to force invalidation of asset caches and restart the application server.

**Comment by i-public** [comment]
deleting the cache-folders did not work, but 

<pre>bundle exec rake assets:precompile RAILS_ENV=production</pre> did the job

we are running production on this server without development

**Comment by tf** [comment]
Ah that makes sense. Did not realize you were talking about development environment.

**Comment by tf** [comment]
I mean production
